import { motion } from "framer-motion";
import { ArrowRight, Brain, Check, FileImage, FileText, GraduationCap, Menu, Sparkles, UploadCloud, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { Logo } from "../components/ui/Logo";
import { ThemeToggle } from "../components/ui/ThemeToggle";

const steps = [["01", "Upload", "Add your notes, slides, images, or question papers."], ["02", "Understand", "StudyMate maps concepts, context, and relationships."], ["03", "Learn", "Read focused notes and ask source-aware questions."], ["04", "Practice", "Check understanding with adaptive quizzes."]];
const faqs = [
  ["What files can I upload?", "StudyMate is designed for PDF, PPT, DOC, text, images, handwritten notes, and question papers."],
  ["Does StudyMate use my own notes?", "Yes. Learning modes are designed to stay grounded in your uploaded material and cite the source page when available."],
  ["Can I use it for programming subjects?", "Yes. Teacher mode supports concept explanations, code walkthroughs, debugging, and step-by-step problem solving."],
];

export default function Landing() {
  const [openFaq, setOpenFaq] = useState(0);
  return <div className="min-h-screen bg-[#f5f5f2] text-[#202025] dark:bg-[#121217] dark:text-[#f5f5f6]">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-black/5 bg-[#f5f5f2]/80 backdrop-blur-xl dark:border-white/8 dark:bg-[#121217]/80"><div className="mx-auto flex h-18 max-w-[1240px] items-center justify-between px-5 sm:px-8"><Logo /><div className="hidden items-center gap-8 text-sm text-[var(--muted)] md:flex"><a href="#how">How it works</a><a href="#modes">Learning modes</a><a href="#faq">FAQ</a></div><div className="flex items-center gap-3"><ThemeToggle/><Link to="/login" className="hidden text-sm font-semibold sm:block">Sign in</Link><Link to="/signup" className="rounded-xl bg-[#26242e] px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-[#1e1d23]">Get started</Link></div></div></nav>
    <section className="relative flex min-h-[920px] overflow-hidden pt-18 lg:min-h-screen">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_25%,rgba(107,92,231,.17),transparent_30%),linear-gradient(to_bottom,transparent_65%,#dcd9f7_100%)] dark:bg-[radial-gradient(circle_at_50%_25%,rgba(118,103,245,.16),transparent_30%)]" />
      <div className="relative mx-auto flex w-full max-w-[1240px] flex-col items-center px-5 pt-20 text-center sm:px-8 lg:pt-24">
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#6558d9]"><Sparkles className="size-4"/> Your notes, made intelligent</motion.div>
        <motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="max-w-4xl text-[50px] font-semibold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[88px]">Study smarter.<br/><span className="text-[#6558d9]">Understand deeper.</span></motion.h1>
        <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .18 }} className="mt-7 max-w-xl text-base leading-7 text-[#686772] sm:text-lg dark:text-[#aaa8b3]">Upload your notes and let StudyMate turn them into personalized learning, teaching, and testing experiences.</motion.p>
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .25 }} className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/signup" className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#6558d9] px-6 text-sm font-semibold text-white shadow-[0_12px_30px_rgba(101,88,217,.28)]">Start learning <ArrowRight className="size-4"/></Link><a href="#how" className="flex h-12 items-center justify-center rounded-xl border border-black/10 bg-white/50 px-6 text-sm font-semibold dark:border-white/10 dark:bg-white/5">Explore StudyMate</a></motion.div>
        <motion.div initial={{ opacity: 0, y: 50, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ delay: .35, duration: .7 }} className="mt-16 w-full max-w-[1050px] overflow-hidden rounded-t-[28px] border border-black/10 border-b-0 bg-[#f7f7fa]/90 p-3 shadow-[0_-5px_80px_rgba(49,42,105,.16)] dark:border-white/10 dark:bg-[#1b1a22]/90">
          <div className="rounded-t-[20px] bg-white p-5 text-left dark:bg-[#201f28] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs text-[#777582]">Good evening, Priyanshu</p><h2 className="mt-1 text-xl font-semibold">What will you master today?</h2></div><div className="grid size-10 place-items-center rounded-xl bg-[#ece9ff] text-[#6558d9]"><Sparkles className="size-5"/></div></div>
          <div className="mt-6 grid gap-3 sm:grid-cols-3">{[[Sparkles,"Learn","Focused notes","#eeeaff"],[GraduationCap,"Teacher","Ask anything","#e7f3ff"],[Brain,"Quiz","Test yourself","#fff1dd"]].map(([Icon,title,desc,color]) => { const C = Icon as typeof Sparkles; return <div key={title as string} className="rounded-2xl border border-black/6 p-5 dark:border-white/8"><div style={{ backgroundColor: color as string }} className="grid size-9 place-items-center rounded-xl text-[#5d51cf]"><C className="size-4"/></div><p className="mt-5 font-semibold">{title as string}</p><p className="mt-1 text-xs text-[#777582]">{desc as string}</p></div>})}</div></div>
        </motion.div>
      </div>
    </section>
    <section id="how" className="bg-[#202027] px-5 py-24 text-white sm:px-8"><div className="mx-auto max-w-[1160px]"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#9990f5]">A simple flow</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.05em] sm:text-5xl">From scattered notes to real understanding.</h2><div className="mt-16 grid gap-px overflow-hidden rounded-2xl bg-white/10 md:grid-cols-4">{steps.map(([number,title,text]) => <div key={number} className="bg-[#202027] p-7"><span className="text-xs font-semibold text-[#9187ee]">{number}</span><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></div>)}</div></div></section>
    <section id="modes" className="px-5 py-24 sm:px-8"><div className="mx-auto max-w-[1160px]"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#6558d9]">Three learning modes</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">One companion. Every way you learn.</h2></div><div className="mt-14 grid gap-10 md:grid-cols-3">{[[Sparkles,"Learn","Structured summaries, definitions, examples, and fast revision."],[GraduationCap,"Teacher","Patient, source-aware explanations and guided problem solving."],[Brain,"Quiz","Personalized practice that finds gaps before the exam does."]].map(([Icon,title,text]) => {const C=Icon as typeof Sparkles;return <div key={title as string} className="border-t border-black/10 pt-7 dark:border-white/10"><C className="size-6 text-[#6558d9]"/><h3 className="mt-8 text-2xl font-semibold">{title as string}</h3><p className="mt-3 text-sm leading-7 text-[#74727d] dark:text-[#aaa8b3]">{text as string}</p><Link to="/signup" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Explore <ArrowRight className="size-4"/></Link></div>})}</div></div></section>
    <section className="border-y border-black/5 bg-white/50 px-5 py-20 dark:border-white/5 dark:bg-white/[.02]"><div className="mx-auto flex max-w-[1160px] flex-col justify-between gap-12 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold tracking-[-.04em]">Bring all your material.</h2><p className="mt-3 text-[#74727d] dark:text-[#aaa8b3]">Slides, notes, scans, and documents belong together.</p></div><div className="flex flex-wrap gap-x-8 gap-y-5 text-sm font-semibold text-[#5e5c67] dark:text-[#c1bec9]">{[[FileText,"PDF"],[FileText,"PPT"],[FileText,"DOC"],[FileImage,"Images"],[UploadCloud,"Handwritten notes"]].map(([Icon,name])=>{const C=Icon as typeof FileText;return <span key={name as string} className="flex items-center gap-2"><C className="size-4 text-[#6558d9]"/>{name as string}</span>})}</div></div></section>
    <section className="px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-[1160px] gap-16 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#6558d9]">Why StudyMate</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Built around how you actually study.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[#74727d] dark:text-[#aaa8b3]">Every answer, note, and quiz stays connected to your learning material, so you spend less time searching and more time understanding.</p></div><div className="divide-y divide-black/10 border-y border-black/10 dark:divide-white/10 dark:border-white/10">{["Personalized learning paths","Source-aware explanations","Adaptive quizzes","Progress and weak-topic tracking"].map(item=><div key={item} className="flex items-center gap-4 py-5 text-sm font-semibold"><span className="grid size-7 place-items-center rounded-full bg-[#6558d9]/10 text-[#6558d9]"><Check className="size-3.5"/></span>{item}</div>)}</div></div></section>
    <section id="faq" className="px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-[1000px] gap-14 md:grid-cols-[.7fr_1.3fr]"><h2 className="text-4xl font-semibold tracking-[-.05em]">Questions,<br/>answered.</h2><div>{faqs.map(([question,answer],i)=><div key={question} className="border-t border-black/10 py-5 dark:border-white/10"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between text-left font-semibold">{question}{openFaq===i?<X className="size-4"/>:<Menu className="size-4"/>}</button>{openFaq===i&&<motion.p initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}} className="max-w-xl pt-4 text-sm leading-7 text-[#74727d] dark:text-[#aaa8b3]">{answer}</motion.p>}</div>)}</div></div></section>
    <footer className="border-t border-black/5 px-5 py-10 dark:border-white/5"><div className="mx-auto flex max-w-[1160px] flex-col justify-between gap-6 sm:flex-row sm:items-center"><Logo/><p className="text-xs text-[#85838c]">Study smarter. Understand deeper. © 2026 StudyMate.</p></div></footer>
  </div>;
}
