import { Bookmark, Check, ChevronDown, Copy, Expand, GraduationCap, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { materials } from "../services/mockData";

const tabs = ["Overview", "Detailed notes", "Exam prep", "Revision"];
export default function Learn() {
  const material=materials[0]; const [tab,setTab]=useState("Overview"); const [bookmarked,setBookmarked]=useState(false);
  return <div><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="section-label">Learn mode</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-[var(--ink)]">{material.title}</h1></div><div className="flex gap-2"><button onClick={()=>setBookmarked(!bookmarked)} className={`grid size-10 place-items-center rounded-xl border border-[var(--border)] ${bookmarked?"bg-[#6558d9] text-white":"bg-[var(--surface)] text-[var(--muted)]"}`}><Bookmark className="size-4"/></button><Link to="/app/teacher" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#6558d9] px-4 text-xs font-semibold text-white"><GraduationCap className="size-4"/>Ask Teacher</Link></div></div>
    <div className="mt-7 flex gap-1 overflow-x-auto border-b border-[var(--border)]">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-xs font-semibold ${tab===item?"border-[#6558d9] text-[#6558d9]":"border-transparent text-[var(--muted)]"}`}>{item}</button>)}</div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[190px_1fr]"><aside className="hidden lg:block"><p className="section-label">Contents</p><nav className="mt-4 space-y-1">{material.topics.map((t,i)=><a key={t.id} href={`#${t.id}`} className={`block rounded-lg px-3 py-2 text-xs ${i===4?"bg-[#6558d9]/10 font-semibold text-[#6558d9]":"text-[var(--muted)] hover:text-[var(--ink)]"}`}>{String(i+1).padStart(2,"0")} {t.title}</a>)}</nav></aside>
      <article className="mx-auto w-full max-w-[760px] rounded-[24px] border border-[var(--border)] bg-[var(--surface)] px-6 py-8 sm:px-10 sm:py-10"><div className="mb-8 flex items-center justify-between"><span className="inline-flex items-center gap-2 text-xs font-semibold text-[#6558d9]"><Sparkles className="size-4"/>AI-structured from your notes</span><div className="flex gap-2"><button className="text-[var(--muted)]"><Copy className="size-4"/></button><button className="text-[var(--muted)]"><Expand className="size-4"/></button></div></div>
      <section><p className="section-label">Smart summary</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[var(--ink)]">Polymorphism</h2><p className="prose-copy mt-5">Object-oriented programming lets us model software as cooperating objects. Polymorphism means “many forms”: the same method call can produce different behavior depending on the object receiving it.</p></section>
      <section className="mt-10"><h3 className="text-lg font-semibold text-[var(--ink)]">Key concepts</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{["One interface, multiple forms","Runtime method selection","Method overloading","Method overriding"].map(text=><div key={text} className="flex items-center gap-3 border-b border-[var(--border)] py-3 text-sm text-[var(--ink)]"><span className="grid size-5 place-items-center rounded-full bg-[#6558d9]/10"><Check className="size-3 text-[#6558d9]"/></span>{text}</div>)}</div></section>
      <section className="mt-10 rounded-2xl border-l-4 border-[#6558d9] bg-[#6558d9]/6 p-6"><p className="text-xs font-bold uppercase tracking-wider text-[#6558d9]">Important definition</p><p className="mt-3 text-sm leading-7 text-[var(--ink)]">Polymorphism is the ability of an object to take on many forms, allowing a common interface to represent different underlying data types.</p></section>
      <section className="mt-10"><h3 className="text-lg font-semibold text-[var(--ink)]">Java example</h3><p className="prose-copy mt-3">A parent reference can point to a child object. Java chooses the overridden method at runtime.</p><div className="mt-5 overflow-hidden rounded-2xl bg-[#202027]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-3 text-[11px] text-white/50"><span>Java</span><button className="flex items-center gap-1"><Copy className="size-3"/>Copy</button></div><pre className="overflow-x-auto p-5 text-[13px] leading-7 text-[#dad7ef]"><code>{`class Animal {\n  void speak() { System.out.println("Sound"); }\n}\n\nclass Dog extends Animal {\n  @Override void speak() {\n    System.out.println("Bark");\n  }\n}`}</code></pre></div></section>
      <section className="mt-10 border-t border-[var(--border)] pt-8"><button className="flex w-full items-center justify-between text-left"><div><p className="section-label">Quick revision</p><p className="mt-2 text-sm font-semibold text-[var(--ink)]">Check the ideas you should remember</p></div><ChevronDown className="size-4 text-[var(--muted)]"/></button></section>
      </article></div>
  </div>;
}
