import { ArrowLeft, Brain, Clock3, FileText, GraduationCap, Sparkles } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { materials } from "../services/mockData";

export default function MaterialDetail() { const { id }=useParams(); const material=materials.find(m=>m.id===id)??materials[0]; const actions=[[Sparkles,"Learn","Structured notes",`/app/learn?material=${material.id}`],[GraduationCap,"Teacher","Ask your tutor",`/app/teacher?material=${material.id}`],[Brain,"Quiz","Test yourself",`/app/quiz?material=${material.id}`]] as const;
  return <div><Link to="/app/materials" className="mb-7 inline-flex items-center gap-2 text-xs font-semibold text-[var(--muted)]"><ArrowLeft className="size-4"/>All materials</Link><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="section-label">{material.subject}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] text-[var(--ink)]">{material.title}</h1><p className="mt-3 text-sm text-[var(--muted)]">Last studied {material.lastStudied}</p></div><div className="flex gap-5 text-xs text-[var(--muted)]"><span className="flex items-center gap-2"><FileText className="size-4"/>{material.pages} pages</span><span className="flex items-center gap-2"><Clock3 className="size-4"/>{material.studyMinutes} min</span></div></div>
    <section className="mt-10"><p className="section-label">Choose a learning mode</p><div className="mt-4 grid gap-4 sm:grid-cols-3">{actions.map(([Icon,title,text,to])=><Link to={to} key={title} className="group rounded-[22px] border border-[var(--border)] bg-[var(--surface)] p-6 transition hover:-translate-y-1 hover:border-[#6558d9]/30 hover:shadow-[0_16px_40px_rgba(68,57,145,.1)]"><Icon className="size-6 text-[#6558d9]"/><h2 className="mt-9 text-xl font-semibold text-[var(--ink)]">{title}</h2><p className="mt-1 text-xs text-[var(--muted)]">{text}</p></Link>)}</div></section>
    <section className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="min-h-[390px] rounded-[22px] border border-[var(--border)] bg-[#282631] p-7 text-white"><div className="mx-auto flex h-full max-w-[440px] flex-col rounded-lg bg-white p-8 text-[#272630] shadow-2xl"><p className="text-xs font-bold text-[#6558d9]">CHAPTER 4</p><h3 className="mt-3 text-2xl font-bold">Polymorphism</h3><div className="mt-6 space-y-3"><span className="block h-2 w-full rounded bg-black/10"/><span className="block h-2 w-[92%] rounded bg-black/10"/><span className="block h-2 w-[70%] rounded bg-black/10"/></div><div className="mt-7 h-20 rounded bg-[#f1effd]"/><p className="mt-auto text-right text-[10px] text-black/40">12</p></div></div><div><div className="flex justify-between"><span className="section-label">Study progress</span><b className="text-sm text-[var(--ink)]">{material.progress}%</b></div><div className="mt-3 h-2 rounded bg-[var(--surface-2)]"><div className="h-full rounded bg-[#6558d9]" style={{width:`${material.progress}%`}}/></div><h3 className="mt-8 text-lg font-semibold text-[var(--ink)]">Detected topics</h3><div className="mt-3 divide-y divide-[var(--border)] border-y border-[var(--border)]">{material.topics.map((t,i)=><div key={t.id} className="flex items-center justify-between py-3 text-sm"><span className="text-[var(--ink)]">{String(i+1).padStart(2,"0")} &nbsp; {t.title}</span><span className="text-xs text-[var(--muted)]">{t.confidence}%</span></div>)}</div></div></section>
  </div>;
}