import { BookCheck, Brain, Clock3, Flame, Target } from "lucide-react";
import { PageTitle } from "../components/ui/PageTitle";
import { WeakTopics } from "../components/progress/WeakTopics";
import { progress } from "../services/mockData";

const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export default function ProgressPage(){ const stats=[["Total study time","14h 24m",Clock3],["Study streak","7 days",Flame],["Questions solved","184",Brain],["Quiz accuracy","82%",Target],["Topics complete","24",BookCheck]] as const;return <div><PageTitle title="Your progress" subtitle="A clear view of your learning, one session at a time."/>
  <div className="grid grid-cols-2 gap-px overflow-hidden rounded-[22px] border border-[var(--border)] bg-[var(--border)] md:grid-cols-5">{stats.map(([label,value,Icon])=><div key={label} className="bg-[var(--surface)] p-5"><Icon className="size-4 text-[#6558d9]"/><p className="mt-6 text-xl font-semibold text-[var(--ink)]">{value}</p><p className="mt-1 text-[11px] text-[var(--muted)]">{label}</p></div>)}</div>
  <div className="mt-8 grid gap-7 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-[22px] border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex justify-between"><div><p className="section-label">Weekly study time</p><h2 className="mt-2 text-lg font-semibold text-[var(--ink)]">6h 26m this week</h2></div><span className="text-xs font-semibold text-emerald-500">+18%</span></div><div className="mt-10 flex h-[220px] items-end justify-between gap-3 border-b border-[var(--border)]">{progress.weeklyMinutes.map((value,i)=><div key={days[i]} className="group flex h-full flex-1 flex-col items-center justify-end"><span className="mb-2 opacity-0 text-[10px] text-[var(--muted)] transition group-hover:opacity-100">{value}m</span><div className="w-full max-w-10 rounded-t-lg bg-[#6558d9]/20 transition hover:bg-[#6558d9]" style={{height:`${value/80*100}%`}}/><span className="mt-3 text-[10px] text-[var(--muted)]">{days[i]}</span></div>)}</div></section>
  <section className="rounded-[22px] border border-[var(--border)] bg-[var(--surface)] p-6"><p className="section-label">Quiz performance</p><h2 className="mt-2 text-lg font-semibold text-[var(--ink)]">Accuracy trend</h2><div className="mt-9 flex h-[180px] items-end gap-2">{progress.weeklyAccuracy.map((value,i)=><div key={i} className="flex flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-md bg-gradient-to-t from-[#6558d9] to-[#a199ef]" style={{height:`${value}%`}}/><span className="text-[9px] text-[var(--muted)]">{value}%</span></div>)}</div></section></div>
  <div className="mt-10 grid gap-10 xl:grid-cols-2"><WeakTopics topics={progress.weakTopics}/><section><p className="section-label">Subject progress</p><h2 className="mt-2 text-xl font-semibold text-[var(--ink)]">Keep the momentum</h2><div className="mt-5 space-y-6">{[["Java OOP",68],["Database systems",44],["Data structures",31]].map(([name,value])=><div key={name as string}><div className="flex justify-between text-sm"><span className="font-medium text-[var(--ink)]">{name}</span><span className="text-[var(--muted)]">{value}%</span></div><div className="mt-2 h-2 rounded bg-[var(--surface-2)]"><div className="h-full rounded bg-[#6558d9]" style={{width:`${value}%`}}/></div></div>)}</div></section></div>
  </div>}
