import { AlertTriangle, ArrowLeft, ArrowRight, Check, RotateCcw, X } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { Link } from "react-router-dom";
import { javaQuiz } from "../services/mockData";

export default function Quiz() {
  const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [submitted,setSubmitted]=useState(false); const [answers,setAnswers]=useState<boolean[]>([]); const [complete,setComplete]=useState(false); const question=javaQuiz.questions[index];
  const submit=()=>{if(selected===null)return;setSubmitted(true);setAnswers(a=>[...a,selected===question.correctIndex]);}; const next=()=>{if(index<javaQuiz.questions.length-1){setIndex(i=>i+1);setSelected(null);setSubmitted(false)}else setComplete(true)};
  if(complete){const score=answers.filter(Boolean).length;return <div className="mx-auto max-w-[760px] py-8 text-center"><p className="section-label">Quiz complete</p><div className="mx-auto mt-7 grid size-40 place-items-center rounded-full border-[12px] border-[#6558d9]/15"><div><p className="text-5xl font-semibold tracking-[-.06em] text-[var(--ink)]">{score}/{answers.length}</p><p className="mt-1 text-xs text-[var(--muted)]">{Math.round(score/answers.length*100)}% accuracy</p></div></div><h1 className="mt-8 text-3xl font-semibold text-[var(--ink)]">Strong finish.</h1><p className="mt-2 text-sm text-[var(--muted)]">You understand the foundations. Review polymorphism before your next attempt.</p><div className="mt-10 grid gap-5 text-left sm:grid-cols-2"><TopicList title="Strong topics" items={["Classes","Objects","Inheritance"]} icon="good"/><TopicList title="Needs revision" items={["Polymorphism","Abstraction"]} icon="weak"/></div><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/app/learn" className="rounded-xl bg-[#6558d9] px-5 py-3 text-sm font-semibold text-white">Review weak topics</Link><button onClick={()=>{setIndex(0);setSelected(null);setSubmitted(false);setAnswers([]);setComplete(false)}} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-5 py-3 text-sm font-semibold text-[var(--ink)]"><RotateCcw className="size-4"/>Try again</button><Link to="/app/materials/java-oop" className="rounded-xl px-5 py-3 text-sm font-semibold text-[var(--muted)]">Back to material</Link></div></div>}
  return <div className="mx-auto max-w-[820px]"><Link to="/app/materials/java-oop" className="inline-flex items-center gap-2 text-xs font-semibold text-[var(--muted)]"><ArrowLeft className="size-4"/>Exit quiz</Link><header className="mt-8"><div className="flex justify-between"><div><p className="section-label">{javaQuiz.title}</p><h1 className="mt-2 text-2xl font-semibold text-[var(--ink)]">Question {index+1} <span className="text-[var(--muted)]">/ {javaQuiz.questions.length}</span></h1></div><span className="text-xs text-[var(--muted)]">{Math.round((index+1)/javaQuiz.questions.length*100)}%</span></div><div className="mt-5 h-1.5 overflow-hidden rounded bg-[var(--surface-2)]"><motion.div className="h-full rounded bg-[#6558d9]" animate={{width:`${(index+1)/javaQuiz.questions.length*100}%`}}/></div></header>
    <AnimatePresence mode="wait"><motion.section key={question.id} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} className="mt-10 rounded-[26px] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-10"><p className="text-xs font-semibold text-[#6558d9]">Multiple choice</p><h2 className="mt-4 text-2xl font-semibold leading-9 tracking-[-.025em] text-[var(--ink)]">{question.prompt}</h2><div className="mt-8 space-y-3">{question.options.map((option,i)=>{const correct=submitted&&i===question.correctIndex;const wrong=submitted&&i===selected&&i!==question.correctIndex;return <button disabled={submitted} onClick={()=>setSelected(i)} key={option} className={`flex w-full items-center gap-4 rounded-2xl border p-4 text-left text-sm transition ${correct?"border-emerald-400 bg-emerald-500/8":wrong?"border-red-400 bg-red-500/8":selected===i?"border-[#6558d9] bg-[#6558d9]/6":"border-[var(--border)] hover:border-[#6558d9]/40"}`}><span className={`grid size-7 place-items-center rounded-full border text-xs ${correct?"border-emerald-500 bg-emerald-500 text-white":wrong?"border-red-500 bg-red-500 text-white":selected===i?"border-[#6558d9] bg-[#6558d9] text-white":"border-[var(--border-strong)] text-[var(--muted)]"}`}>{correct?<Check className="size-3.5"/>:wrong?<X className="size-3.5"/>:String.fromCharCode(65+i)}</span><span className="text-[var(--ink)]">{option}</span></button>})}</div>{submitted&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`mt-7 rounded-2xl p-5 ${selected===question.correctIndex?"bg-emerald-500/8":"bg-amber-500/8"}`}><p className="flex items-center gap-2 text-sm font-semibold text-[var(--ink)]">{selected===question.correctIndex?<Check className="size-4 text-emerald-500"/>:<AlertTriangle className="size-4 text-amber-500"/>}{selected===question.correctIndex?"Correct":"Not quite"}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{question.explanation}</p><p className="mt-3 text-[11px] text-[var(--muted)]">Based on: {question.source}</p></motion.div>}<div className="mt-8 flex justify-end">{!submitted?<button disabled={selected===null} onClick={submit} className="rounded-xl bg-[#6558d9] px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">Submit answer</button>:<button onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-[#6558d9] px-6 py-3 text-sm font-semibold text-white">{index===javaQuiz.questions.length-1?"View results":"Next question"}<ArrowRight className="size-4"/></button>}</div></motion.section></AnimatePresence>
  </div>;
}
function TopicList({title,items,icon}:{title:string;items:string[];icon:"good"|"weak"}) {return <div className="border-t border-[var(--border)] pt-5"><p className="text-sm font-semibold text-[var(--ink)]">{title}</p><div className="mt-4 space-y-3">{items.map(i=><p key={i} className="flex items-center gap-2 text-sm text-[var(--muted)]">{icon==="good"?<Check className="size-4 text-emerald-500"/>:<AlertTriangle className="size-4 text-amber-500"/>}{i}</p>)}</div></div>}