import { ArrowUp, BookOpen, Code2, GraduationCap, Lightbulb, Mic, Paperclip, Sparkles } from "lucide-react";
import { FormEvent, useRef, useState } from "react";
import { motion } from "framer-motion";
import type { ChatMessage } from "../types";
import { initialMessages } from "../services/mockData";
import { teacherService } from "../services/teacherService";

const prompts = [[Lightbulb,"Explain polymorphism"],[BookOpen,"Solve a question"],[Code2,"Explain my code"],[Sparkles,"Give me an example"]] as const;
export default function Teacher() {
  const [messages,setMessages]=useState<ChatMessage[]>(initialMessages); const [value,setValue]=useState(""); const [sending,setSending]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const send=async(event?:FormEvent)=>{event?.preventDefault();if(!value.trim()||sending)return;const text=value;setValue("");setMessages(m=>[...m,{id:crypto.randomUUID(),role:"user",content:text,createdAt:"Now"}]);setSending(true);const response=await teacherService.sendMessage(text);setMessages(m=>[...m,response]);setSending(false)};
  return <div className="-my-7 flex h-[calc(100vh-68px)] flex-col sm:-my-10"><header className="border-b border-[var(--border)] py-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#6558d9] text-white"><GraduationCap className="size-5"/></span><div><h1 className="font-semibold text-[var(--ink)]">StudyMate Teacher</h1><p className="text-xs text-[var(--muted)]">Your personal AI tutor · Java OOP Notes</p></div></div></header>
    <div className="flex-1 overflow-y-auto py-7"><div className="mx-auto max-w-[760px] space-y-6">{messages.map((message,index)=><motion.div key={message.id} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`flex gap-3 ${message.role==="user"?"justify-end":""}`}>{message.role==="assistant"&&<span className="grid size-8 shrink-0 place-items-center rounded-xl bg-[#6558d9] text-white"><Sparkles className="size-4"/></span>}<div className={message.role==="user"?"max-w-[80%] rounded-2xl rounded-tr-sm bg-[#6558d9] px-5 py-3 text-sm leading-6 text-white":"max-w-[88%]"}><p className={`whitespace-pre-line text-sm leading-7 ${message.role==="assistant"?"text-[var(--ink)]":""}`}>{message.content}</p>{message.role==="assistant"&&index===0&&<div className="mt-6 grid gap-2 sm:grid-cols-2">{prompts.map(([Icon,text])=><button key={text} onClick={()=>setValue(text)} className="flex items-center gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 text-left text-xs font-medium text-[var(--ink)] hover:border-[#6558d9]/40"><Icon className="size-4 text-[#6558d9]"/>{text}</button>)}</div>}{message.source&&<p className="mt-4 text-[11px] text-[var(--muted)]">Based on your uploaded notes · {message.source}</p>}</div></motion.div>)}{sending&&<div className="flex items-center gap-2 text-xs text-[var(--muted)]"><span className="size-1.5 animate-pulse rounded-full bg-[#6558d9]"/><span>StudyMate is responding...</span></div>}</div></div>
    <div className="border-t border-[var(--border)] bg-[var(--bg)] py-4"><form onSubmit={send} className="mx-auto flex max-w-[760px] items-end gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-2 shadow-[0_10px_30px_rgba(30,27,60,.06)]"><input ref={fileRef} type="file" accept="image/*,.pdf,.doc,.docx,.txt" className="hidden"/><button type="button" onClick={()=>fileRef.current?.click()} className="grid size-10 place-items-center text-[var(--muted)]" aria-label="Attach file"><Paperclip className="size-4"/></button><textarea value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} rows={1} placeholder="Ask StudyMate..." className="max-h-28 min-h-10 flex-1 resize-none bg-transparent py-2.5 text-sm text-[var(--ink)] outline-none placeholder:text-[var(--muted)]"/><button type="button" className="grid size-10 place-items-center text-[var(--muted)]"><Mic className="size-4"/></button><button disabled={!value.trim()} className="grid size-10 place-items-center rounded-xl bg-[#6558d9] text-white disabled:opacity-40"><ArrowUp className="size-4"/></button></form><p className="mx-auto mt-2 max-w-[760px] text-center text-[10px] text-[var(--muted)]">Source-grounded answers require a connected StudyMate API.</p></div>
  </div>;
}
